#define SOLARUS_MAJOR_VERSION 1
#define SOLARUS_MINOR_VERSION 5
#define SOLARUS_PATCH_VERSION 3

#ifndef SOLARUS_MINOR_VERSION
#define SOLARUS_MINOR_VERSION 0
#endif

#ifndef SOLARUS_PATCH_VERSION
#define SOLARUS_PATCH_VERSION 0
#endif

#define HAVE_UNISTD_H
